### ISSUE TITLE
Incorrect dependencies

### ISSUE THREAD

**Issue by DManowitz** [conda-forge/slotscheck-feedstock#20]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The dependencies for this package in conda-forge don't match up with those in the package's [pyproject.toml](https://github.com/ariebovenberg/slotscheck/blob/v0.16.5/pyproject.toml) file in its github repo.  For example, in conda-forge, there is a dependency on `importlib-metadata >=1,<5`.  However, in the pyproject.toml file, it states `importlib-metadata = {version = ">=1,<6", python = "<3.8"}` as a dependency.

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by thewchan** [comment]
Thanks, fixed in #21
